# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true


Style/HashSyntax:
  Exclude:
    - 'lib/tasks/check_overlapping_bookings.rake'


Style/StringLiterals:
  Enabled: false


Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'db/seeds.rb'
